### ISSUE TITLE
Use of acronym POV and publisher name

### ISSUE THREAD

**Issue by damianooldoni** [riparias/pov-ias-plants-occurrences#16]
I set both `rightsHolder` and `institutionCode` equal to `"POV"`. Although, the acronym POV is not present in the official name of the GBIF publisher, [Province East-Flanders](https://www.gbif.org/publisher/e22b5484-d879-43ed-a923-082dcc28d6f7). Also in the publisher description, POV is never mentioned. Should we use then another value for `rightsHolder` and `institutionCode`? I don't think so. As consequence, I have some publisher related questions:

1. Shouldn't we add the acronym to the publisher name? Notice that the acronym of the organisation is present for both [VMM](https://www.gbif.org/publisher/ec5f9a9c-09b0-4da3-ae8e-22627620fff6) and [INBO](https://www.gbif.org/publisher/1cd669d0-80ea-11de-a9d0-f1765f95f18b). This eases also the search of the publisher, i.e. by typing the acronym in https://www.gbif.org/publisher/search page.

2. I think that the English name and so the official publisher name on GBIF should be Province East Flanders instead of Province East-Flanders. In other words, the hyphen (-) should be removed. See similar situations, e.g. [West Virginia](https://en.wikipedia.org/wiki/West_Virginia), [North Dakota](https://en.wikipedia.org/wiki/North_Dakota) and others in USA and [East Midlands](https://en.wikipedia.org/wiki/East_Midlands) and [West Midlands](https://en.wikipedia.org/wiki/West_Midlands) in UK.

@dimEvil, as GBIF node manager and POV's  publisher technical contact: what do you think about it?
Of course, @peterdesmet and @LienReyserhove, if you have time and want to give your opinion, you are always welcome.

**Comment by damianooldoni** [comment]
rightsHolder and institutionCode are not anymore POV, but PCM. Removing the hyphen in "East-Flanders" publisher name is not an issue of this dataset.

**Comment by peterdesmet** [comment]
Decided to use the acronym POV after all.
