### ISSUE TITLE
Upload metadata

### ISSUE THREAD

**Issue by damianooldoni** [riparias/pov-ias-plants-occurrences#37]
Dataset metadata are in this [gdoc document](https://docs.google.com/document/d/1wMRiRp42dtAZnyolJDfdi7ilA21NQJ--LmFpLwUB-aY/edit). Lien, notice that I changed the title (suggesting mode) as @peterdesmet suggested in his DwC mapping review (see #17).

**Comment by damianooldoni** [comment]
The new proposed title is _Monitoring of invasive alien species by PRM in East Flanders, Belgium_.
 
The previous title was _Monitoring of invasive alien species by the Provincial Center of Environmental Research, Province East-Flanders, BelgiumMonitoring of invasive alien species by PRM in East Flanders, Belgium_

I don't know why, but I slightly prefer the previous one, which is actually the title you chose. @LienReyserhove: I let you decide about this.

If you opt for the old title, please, let me know: I will change it in the SQL mapping as well and I will rerun the pipeline.

**Comment by damianooldoni** [comment]
To notice also that we have now PCM instead of POV as `rightsHolder` and `institutionCode` in the mapping. Here the [reason](https://github.com/riparias/pov-ias-plants-occurrences/issues/17#issuecomment-1278811544).

**Comment by LienReyserhove** [comment]
I prefer this title: `Monitoring of invasive alien species by the Provincial Center of Environmental Research, Province East-Flanders, Belgium`
Reason: I wouldn't use the abbrevation, it's quite meaningless.

**Comment by damianooldoni** [comment]
Thanks @LienReyserhove. I agree with your title and the reason yuo gave.

**Comment by peterdesmet** [comment]
If the scope is not East Flanders, name it `(PCM) in Flanders, Belgium` or `(PCM) in Belgium`.

**Comment by LienReyserhove** [comment]
Agree, I think it's best to keep the East Flanders, so that would make it:

`Monitoring of invasive alien species by the Provincial Center of Environmental Research (PCM) in East Flanders, Belgium`
