### ISSUE TITLE
License correct?

### ISSUE THREAD

**Issue by LienReyserhove** [riparias/pov-ias-plants-occurrences#48]
While inspecting the dataset, I found this license: https://creativecommons.org/licenses/by-nc/4.0/legalcode.
This conflicts with the license in the metadata, which is CC BY. I would also suggest the last one, not the CC BY-NC.
Why did we choose for the CC BY-NC?

See also https://github.com/riparias/pov-fishes-occurrences/issues/29

**Comment by damianooldoni** [comment]
I asked via mail to @filipmahieu

**Comment by damianooldoni** [comment]
@filipmahieu answer:
> We nemen de CC-BY-licentie. Deze link meen ik. https://creativecommons.org/licenses/by/4.0/legalcode.nl

**Comment by damianooldoni** [comment]
New run of the DwC mapping has solved this issue.
