### ISSUE TITLE
How to map surface/coverage

### ISSUE THREAD

**Issue by damianooldoni** [riparias/pov-ias-plants-occurrences#9]
We have the following two columns:

QuantificationOfInvasion | QuantificationUnit
--- | ---
25 | m²
300 | m²
... | m²

where `m²` is the measurement unit of a surface covered by the plants.

`QuantificationOfInvasion` fits perfectly the DwC field `organismQuantity`. But how to map `m²` in a simple occurrence core? @LienReyserhove and I are sure that it should be mapped in the field `organismQuantityType`. See https://dwc.tdwg.org/terms/#dwc:organismQuantityType.

We actually miss the field `organismQuantityUnit`, similar to the `measurementUnit` in the MoF extension.

@LienReyserhove and I found some mapping options, but no one satisfies both of us at the same time:

- `organismQuantity` = `surface (m²)`
- `organismQuantity` = `(m²)`
- `organismQuantity` = `coverage (m²)`

@peterdesmet, @DimEvil: what do you think about it? Thanks.

**Comment by damianooldoni** [comment]
Option proposed by @DimEvil:
OrganismQuantity : `25`
OrganismQuantityType: `m²`

**Comment by peterdesmet** [comment]
I'm tempted to follow @dimEvil and go for `25` + `m²` or `25` + `square meter`

**Comment by damianooldoni** [comment]
Other possibility from @peterdesmet: `25` + `coverage in square meter`.

**Comment by damianooldoni** [comment]
I give my :+1 for the last proposal.

**Comment by DimEvil** [comment]
The square meter is the [SI-derived unit](https://simple.wikipedia.org/wiki/International_System_of_Units#Derived_units) of [area](https://simple.wikipedia.org/wiki/Area). It has a symbol m² (33A1 in [Unicode](https://simple.wikipedia.org/wiki/Unicode)[[1]](https://simple.wikipedia.org/wiki/Square_metre#cite_note-1)). It is defined as the area of a [square](https://simple.wikipedia.org/wiki/Square_(geometry)) whose sides measure exactly one metre.

so m² is totally acceptable and uses official units 🖌️

**Comment by damianooldoni** [comment]
Thanks @DimEvil! I think I will opt for: `25` + `coverage in m²`.
